@startuml
abstract class Metric {
  - isBatched: boolean

  + calculate(...): Result
  # _preprocess(...): ProcessedData
  # _calculateCore(processed_data: ProcessedData): Result
  + isBatched(): boolean
}

class OrographyRMSE {
  - usetorch: boolean

  + preprocess(real_data: RealData, fake_data: FakeData, obs_data: ObsData): ProcessedData
  + calculateCore(processed_data: ProcessedData): Result
}
Metric <|-- OrographyRMSE
abstract class Configurable {
  + fromConfig(config_data: Union[str, Dict]): Configurable
}

class Preprocessor extends Configurable {
  + process_batch(batch: List): ProcessedBatch
}

class MemoryCache {
  - cache: Dict

  + add_to_cache(key: str, data: Any): void
  + is_cached(key: str): boolean
}

abstract class Dataset extends Configurable {
  - data_folder: str

  # load_data(file_path: str): RawData
  + preprocess_batch(batch: List): ProcessedBatch
  + is_dataset_cached(): boolean
  + __get__(index): data
}

class RealDataset extends Dataset {
  + __get__(date): data
  + load_data(file_path: str): RealData
}

class FakeDataset extends Dataset {
  + load_data(file_path: str): FakeData
}

class ObsDataset extends Dataset {
  + __get__(date): data
  + load_data(file_path: str): ObsData
}

class DataLoader extends Configurable {
  - data_length: int
  - current_index: int

  + __iter__(): Iterator
  + __next__(): Tuple[ProcessedBatch, ProcessedBatch, ProcessedBatch]
  + __len__(): int
  - _collate_fn(batch: List): Tuple[ProcessedBatch, ProcessedBatch, ProcessedBatch]
}

class ExperimentSet extends Configurable {
  - dataloader: DataLoader

  + run(index: int): void
}

class MainProcess {
  - datasets: List[Dataset]
  - metrics: List[Metric]
  - preprocessor: Preprocessor
  - config: GlobalConfig

  + setPreprocessor(preprocessor: Preprocessor): void
  + setGlobalConfig(config: GlobalConfig): void
  + runExperiments(sets: List[ExperimentSet>): void
}

Metric <|-- MetricB
Preprocessor <|-- BasicPreprocessor
Preprocessor <|-- AdvancedPreprocessor
Dataset o-- "1" MemoryCache
MainProcess o-- "n" ExperimentSet
ExperimentSet o-- DataLoader
DataLoader o-- "1" RealDataset
DataLoader o-- "1" FakeDataset
DataLoader o-- "1" ObsDataset
Dataset o-- "1" Preprocessor
ExperimentSet o-- "n" Metric
@enduml
