name: Experiment1
dataloaders:
  batch_size: 1
  path_to_csv: data/IS_1_1.0_0_0_0_0_0_256_large_lt_done_reduced
  csv_file: Large_lt_test_labels.csv
  date_start: '2021-08-14'
  date_end: '2021-08-15'
  Lead_Times : 15
  start_time : 21 # 21:00. Arome simulations in the dataset start at 21:00 
  dh : 3 
  real_dataset_config:
    name: DatasetReal
    data_folder: data/IS_1_1.0_0_0_0_0_0_256_large_lt_done_reduced
    preprocessor_config:
      name: BasicPreprocessor
      args:
        arg1: value1
        arg2: value2
  fake_dataset_config:
    name: DatasetFake
    data_folder: data/normal_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']_reduced/samples
    preprocessor_config:
      name: Preprocessor
      args:
        arg1: value1
        arg2: value2
  obs_dataset_config:
    name: DatasetObs
    data_folder: data/obs_reduced_npy
    crop_indices: [180, 436, 500, 756]
    preprocessor_config:
      name: Preprocessor
      args:
        arg1: value1
        arg2: value2
metrics_list:
  - name: W1RandomNUMPY
    type: W1RandomNUMPY
output_path: experiment1_output