name: Experiment1
debiasing : True
debiasing_mode : ENSAVG
conditioning_members : 16
threshold_ff : [1.39, 2.78, 4.17, 5.56, 8.33, 11.11]
threshold_t2m : [278.15, 283.15, 288.15, 293.15, 297.15, 303.15]

dataloaders:
  batch_size: 1
  maxNsamples: 16
  path_to_csv: data/IS_1_1.0_0_0_0_0_0_256_large_lt_done_reduced
  csv_file: Large_lt_test_labels.csv
  date_start: '2021-08-14'
  date_end: '2021-08-15'
  Lead_Times : 15
  start_time : 21 # 21:00. Arome simulations in the dataset start at 21:00 
  dh : 3 
  real_dataset_config:
      
    name: DatasetReal
    data_folder: data/IS_1_1.0_0_0_0_0_0_256_large_lt_done_reduced
    variables: ['u','v','t2m']
    sizeH: 256
    sizeW: 256
    var_indices: [1,2,3] #where to find the variables in dataset samples
    crop_indices: [0,256,0,256]
    preprocessor_config:
        name: Preprocessor
        variables: ['u','v','t2m']
        real_var_indices: [1,2,3] #where to find the variables in stat files
        configDir: /scratch/mrmn/moldovang/MetScore/
        configFile: real_processor_config_model.yml
        real_data_dir: data/IS_1_1.0_0_0_0_0_0_256_large_lt_done_reduced

  fake_dataset_config:
    name: DatasetFake
    data_folder: data/normal_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']_reduced/samples
    variables: ['u','v','t2m']
    sizeH: 256
    sizeW: 256
    var_indices: [0,1,2] #where to find the variables in dataset samples
    crop_indices: [0,256,0,256]
    preprocessor_config:
        name: ReverserrPreprocessor
        variables: ['u','v','t2m']
        real_var_indices: [1,2,3] #where to find the variables in stat files
        configDir: /scratch/mrmn/moldovang/MetScore/
        configFile: fake_processor_config_model.yml
        real_data_dir: data/IS_1_1.0_0_0_0_0_0_256_large_lt_done_reduced
    
  obs_dataset_config:
    name: DatasetObs
    data_folder: data/obs_reduced_npy
    crop_indices: [180, 436, 500, 756]
    variables: ['ff','dd','t2m']
    var_indices: [0,1,2]
    crop_indices: [180,436,500,756]
    preprocessor_config:
        name: Preprocessor
        variables: ['ff','dd','rr']
        real_var_indices: [0,1,2]
        configDir: /where/to/find/configFile/
        configFile: obs_processor_config_model.yml

metrics_list:
  - name: relDiagram
    type: relDiagram
  - name: ensembleCRPS
    type: ensembleCRPS
  - name: brierScore
    type: brierScore
  - name: skillSpread
    type: skillSpread
  - name: rankHistogram
    type: rankHistogram
  - name: biasEnsemble
    type: biasEnsemble


output_path: experiment1_output

