name: Experiment1
real_dataset_config:
  name: DatasetReal
  data_folder: /scratch/mrmn/moldovang/databases/IS_1_1.0_0_0_0_0_0_256_large_lt_done_reduced
  batch_size: 1
  preprocessor_config:
    name: BasicPreprocessor
    args:
      arg1: value1
      arg2: value2
fake_dataset_config:
  name: DatasetFake
  data_folder: /scratch/mrmn/moldovang/tests_CGAN/normal_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']_reduced/samples
  batch_size: 1
  preprocessor_config:
    name: Preprocessor
    args:
      arg1: value1
      arg2: value2
obs_dataset_config:
  name: DatasetObs
  data_folder: /scratch/mrmn/moldovang/obs_databases/obs_reduced_npy
  batch_size: 1
  crop_indices: [180, 436, 500, 756]
  preprocessor_config:
    name: Preprocessor
    args:
      arg1: value1
      arg2: value2
metrics_list:
  - name: OrographyRMSE
    type: OrographyRMSE
  - name: OrographyRMSE-2
    type: OrographyRMSE
output_path: experiment1_output