name: Experiment1
real_dataset_config:
  name: DatasetReal
  data_folder: samples
  label_file: labels.csv
  batch_size: 32
  variables: ['u','v','t2m']
  sizeH: 256
  sizeW: 256
  var_indices: [1,2,3] #where to find the variables in dataset samples
  crop_indices: [0,256,0,256]
  preprocessor_config:
    name: BasicPreprocessor
    configFile: real_processor_config_model.yml
fake_dataset_config:
  name: DatasetFake
  data_folder: samples/
  batch_size: 32
  variables: ['u','v','t2m']
  sizeH: 256
  sizeW: 256
  var_indices: [0,1,2] #where to find the variables in dataset samples
  crop_indices: [0,256,0,256]
  preprocessor_config:
    name: Preprocessor
    configFile: fake_processor_config_model.yml
obs_dataset_config:
  name: DatasetObs
  data_folder: samples
  label_file: labels.csv
  batch_size: 32
  variables: ['ff','dd','t2m']
  var_indices: [0,1,2]
  crop_indices: [180,436,500,756]
  preprocessor_config:
    name: Preprocessor
    configFile: obs_processor_config_model.yml
metrics_list:
  - name: OrographyRMSE
    type: OrographyRMSE
  - name: OrographyRMSE-2
    type: OrographyRMSE
output_path: experiment1_output