output_folder: /scratch/mrmn/brochetc/GAN_2D/experiments_rain
experiments:
  - name: Experiment_random_dataset_100k_test
    dataloaders:
      type: RandomDataloader #choosing between Dataloader (base class), RandomDataloader and DateDataloader
      batch_size: 1
      maxNsamples: 512
      real_dataset_config:
        batch_size: 128
        data_folder: /scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/cropped_120_376_540_796/
        variables: ['u','v','t2m']
        filename_format: _sample{index}
        sizeH: 256
        sizeW: 256
        file_size: 1
        var_indices: [0,1,2,3] #where to find the variables in dataset samples
        crop_indices: [0,256,0,256]
        preprocessor_config:
          type: Preprocessor
          real_var_indices: [0,1,2,3] #where to find the variables in stat files
          real_data_dir: /scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/cropped_120_376_540_796/
          stat_folder: "stat_files/"
          stat_version: "rr" # the name of the stat file is for ex: 'mean_[stat_version]_log_ppx.npy'
          rr_transform:
            log_transform_iteration: 1
            symetrization: False
            gaussian_std: 0 # Threshold between rain and no rain to add a gaussian noise where rr < gaussian_std.
          normalization:
            type: "mean"
            per_pixel: False
            for_rr:
              blur_iteration: 1
      fake_dataset_config:
        type: FakeDataset #choosing between FakeDataset and MixDataset. For RandomDataloader, is only RandomDataset
        batch_size: 1
        file_size: 128
        data_folder: /scratch/mrmn/brochetc/GAN_2D/Instance_7/samples_gen/
        variables: ['rr','u','v','t2m']
        sizeH: 256
        sizeW: 256
        step: 100000 
        filename_format: _Fsample_100000_{index}
        var_indices: [0,1,2,3] #where to find the variables in dataset samples
        crop_indices: [0,256,0,256]
        preprocessor_config:
          type: ReverserrPreprocessor
          real_var_indices: [0,1,2,3] #where to find the variables in stat files
          real_data_dir:  /scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/cropped_120_376_540_796/
          stat_folder: "stat_files/"
          stat_version: "rr" # the name of the stat file is for ex: 'mean_[stat_version]_log_ppx.npy'
          rr_transform:
            log_transform_iteration: 1
            symetrization: False
            gaussian_std: 0
          normalization:
            type: "mean"
            per_pixel: False
            for_rr:
              blur_iteration: 1
      obs_dataset_config:
        data_folder: /scratch/mrmn/brochetc/obs_databases/obs_full_npy
        crop_indices: [180, 436, 500, 756]
        variables: ['ff','dd','t2m']
        var_indices: [0,1,2]
        preprocessor_config:
            type: Preprocessor
    metrics:
      args:
        debiasing: False
        debiasing_mode: ENSAVG
        conditioning_members: 16
        threshold: [[ 1.39, 2.78, 4.17, 5.56, 8.33, 11.11 ], [ 278.15, 283.15, 288.15, 293.15, 297.15, 303.15 ]] ## [ff], [t2m] 
        var_channel: 1
        obs_var_channel: 1
        rr_idx: 0
      metrics_list:
        - name: varianceReal
          type: variance
          isOnReal: True
        - name: variance
          type: variance
          isOnReal: False
        - name: AreaProportion
          type: AreaProportion
          isOnReal: False
