type: ReverserrPreprocessor
real_var_indices: [1,2,3] #where to find the variables in stat files
real_data_dir: data/IS_1_1.0_0_0_0_0_0_256_large_lt_done_reduced
stat_folder: "stat_files/"
stat_version: "rr" # the name of the stat file is for ex: 'mean_[stat_version]_log_ppx.npy'
rr_transform:
  log_transform_iteration: 1
  symetrization: False
  gaussian_std: 0
normalization:
  type: "mean"
  per_pixel: False
  for_rr:
    blur_iteration: 1
