name: normal_reduced_test
batch_size: 32
real_dataset_config:
  name: DatasetReal
  data_folder: /gpfsscratch/rech/woz/commun/data_reduced/IS_1_1.0_0_0_0_0_0_256_large_lt_done_reduced/
  label_file: small_selected.csv
  batch_size: 32
  variables: ['u','v','t2m']
  sizeH: 256
  sizeW: 256
  var_indices: [1,2,3] #where to find the variables in dataset samples
  crop_indices: [0,256,0,256]
  preprocessor_config:
    name: ForwardrrPreprocessor
    variables: ['u','v','t2m']
    real_var_indices: [1,2,3] #where to find the variables in stat files
    configDir: /linkhome/rech/genlxx01/ult26bn/MetScore/
    configFile: real_processor_config_model.yml
fake_dataset_config:
  name: DatasetFake
  data_folder: /gpfsscratch/rech/woz/commun/data_reduced/normal_reduced/samples/
  label_file: 
  batch_size: 32
  variables: ['u','v','t2m']
  sizeH: 256
  sizeW: 256
  var_indices: [0,1,2] #where to find the variables in dataset samples
  crop_indices: [0,256,0,256]
  preprocessor_config:
    name: Preprocessor
    variables: ['u','v','t2m']
    real_var_indices: [1,2,3] #where to find the variables in stat files
    configDir: /linkhome/rech/genlxx01/ult26bn/MetScore/
    configFile: fake_processor_config_model.yml
obs_dataset_config:
  name: DatasetObs
  data_folder: /gpfsscratch/rech/woz/commun/data_reduced/obs_reduced_npy/
  label_file: labels.csv
  batch_size: 32
  variables: ['ff','dd','t2m']
  var_indices: [0,1,2]
  crop_indices: [180,436,500,756]
  preprocessor_config:
    name: Preprocessor
    variables: ['ff','dd','rr']
    real_var_indices: [1,2,3]
    configDir: /linkhome/rech/genlxx01/ult26bn/MetScore/
    configFile: obs_processor_config_model.yml
metrics_list:
  - name: W1CenterNUMPY
    type: W1CenterNUMPY
  - name: spectralCompute
    type: spectralCompute
  - name: SWDallTorch
    type: SWDallTorch
output_path: /gpfsscratch/rech/woz/commun/data_reduced/normal_reduced/log/